### ISSUE TITLE
Feature request: Alternative command prefix

### ISSUE THREAD

**Issue by Uular** [heppu/irc-bot#2]
Typing the exclamation mark `!` requires a modifier key on most standard keyboard layouts. It would be nice to be able to use a single-key prefix as an alternative of the exclamation. My suggestion is the period `.` which is conveniently located on most layouts.

Thus you could write
`!ops`
as
`.ops`
Which is 17% less keys pressed (including the newline to post) for the same result. Clearly more efficient!

**Comment by heppu** [comment]
#7
